# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - workspace: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - storage-box: "npm"
    directory: "/packages/storage-box"
    schedule:
      interval: "daily"
  - drive-fs: "npm"
    directory: "/packages/fs-drive"
    schedule:
      interval: "daily"
  - example-basic: "npm"
    directory: "/examples/basic"
    schedule:
      interval: "daily"
