name: spry_starter
description: Spry 
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  spry: ^0.1.4
  spry_interceptor: ^0.1.0
  spry_json: ^0.1.1
  spry_router: ^0.3.2

dev_dependencies:
  http: ^0.13.5
  http_methods: ^1.1.0
  lints: ^2.0.0
  spry_fsrouter: ^0.1.0
  test: ^1.22.2
