name: spry_starter
description: Spry 
version: 1.0.0
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  spry: ^0.5.0
  spry_interceptor: ^1.0.0
  spry_json: ^1.0.0
  spry_router: ^1.0.0

dev_dependencies:
  http: ^0.13.6
  http_methods: ^1.1.1
  lints: ^2.0.0
  spry_fsrouter: ^1.0.0
  test: ^1.24.2
