import { PluginFunction, Component } from 'vue';
import { HeroiconsPluginOptions } from './lib';

export { HeroiconsPluginOptions } from './lib';

export declare const HeroiconsAdjustmentsOutline: Component;
export declare const HeroiconsAnnotationOutline: Component;
export declare const HeroiconsArchiveOutline: Component;
export declare const HeroiconsArrowCircleDownOutline: Component;
export declare const HeroiconsArrowCircleLeftOutline: Component;
export declare const HeroiconsArrowCircleRightOutline: Component;
export declare const HeroiconsArrowCircleUpOutline: Component;
export declare const HeroiconsArrowDownOutline: Component;
export declare const HeroiconsArrowLeftOutline: Component;
export declare const HeroiconsArrowNarrowDownOutline: Component;
export declare const HeroiconsArrowNarrowLeftOutline: Component;
export declare const HeroiconsArrowNarrowRightOutline: Component;
export declare const HeroiconsArrowNarrowUpOutline: Component;
export declare const HeroiconsArrowRightOutline: Component;
export declare const HeroiconsArrowUpOutline: Component;
export declare const HeroiconsAtSymbolOutline: Component;
export declare const HeroiconsBadgeCheckOutline: Component;
export declare const HeroiconsBanOutline: Component;
export declare const HeroiconsBellOutline: Component;
export declare const HeroiconsBookOpenOutline: Component;
export declare const HeroiconsBookmarkAltOutline: Component;
export declare const HeroiconsBookmarkOutline: Component;
export declare const HeroiconsBriefcaseOutline: Component;
export declare const HeroiconsCalendarOutline: Component;
export declare const HeroiconsCameraOutline: Component;
export declare const HeroiconsCashOutline: Component;
export declare const HeroiconsChartBarOutline: Component;
export declare const HeroiconsChartPieOutline: Component;
export declare const HeroiconsChartSquareBarOutline: Component;
export declare const HeroiconsChatAlt2Outline: Component;
export declare const HeroiconsChatAltOutline: Component;
export declare const HeroiconsChatOutline: Component;
export declare const HeroiconsCheckCircleOutline: Component;
export declare const HeroiconsCheckOutline: Component;
export declare const HeroiconsChevronDownOutline: Component;
export declare const HeroiconsChevronLeftOutline: Component;
export declare const HeroiconsChevronRightOutline: Component;
export declare const HeroiconsChevronUpOutline: Component;
export declare const HeroiconsClipboardCheckOutline: Component;
export declare const HeroiconsClipboardCopyOutline: Component;
export declare const HeroiconsClipboardListOutline: Component;
export declare const HeroiconsClipboardOutline: Component;
export declare const HeroiconsClockOutline: Component;
export declare const HeroiconsCloudDownloadOutline: Component;
export declare const HeroiconsCloudUploadOutline: Component;
export declare const HeroiconsCodeOutline: Component;
export declare const HeroiconsCogOutline: Component;
export declare const HeroiconsCollectionOutline: Component;
export declare const HeroiconsColorSwatchOutline: Component;
export declare const HeroiconsCreditCardOutline: Component;
export declare const HeroiconsCurrencyDollarOutline: Component;
export declare const HeroiconsCurrencyEuroOutline: Component;
export declare const HeroiconsCurrencyPoundOutline: Component;
export declare const HeroiconsCurrencyRupeeOutline: Component;
export declare const HeroiconsCurrencyYenOutline: Component;
export declare const HeroiconsCursorClickOutline: Component;
export declare const HeroiconsDesktopComputerOutline: Component;
export declare const HeroiconsDocumentAddOutline: Component;
export declare const HeroiconsDocumentDownloadOutline: Component;
export declare const HeroiconsDocumentDuplicateOutline: Component;
export declare const HeroiconsDocumentRemoveOutline: Component;
export declare const HeroiconsDocumentReportOutline: Component;
export declare const HeroiconsDocumentOutline: Component;
export declare const HeroiconsDotsCircleHorizontalOutline: Component;
export declare const HeroiconsDotsHorizontalOutline: Component;
export declare const HeroiconsDotsVerticalOutline: Component;
export declare const HeroiconsDownloadOutline: Component;
export declare const HeroiconsDuplicateOutline: Component;
export declare const HeroiconsEmojiHappyOutline: Component;
export declare const HeroiconsEmojiSadOutline: Component;
export declare const HeroiconsExclamationCircleOutline: Component;
export declare const HeroiconsExclamationOutline: Component;
export declare const HeroiconsExternalLinkOutline: Component;
export declare const HeroiconsEyeOffOutline: Component;
export declare const HeroiconsEyeOutline: Component;
export declare const HeroiconsFilterOutline: Component;
export declare const HeroiconsFlagOutline: Component;
export declare const HeroiconsFolderOutline: Component;
export declare const HeroiconsGlobeAltOutline: Component;
export declare const HeroiconsGlobeOutline: Component;
export declare const HeroiconsHashtagOutline: Component;
export declare const HeroiconsHeartOutline: Component;
export declare const HeroiconsHomeOutline: Component;
export declare const HeroiconsInboxInOutline: Component;
export declare const HeroiconsInboxOutline: Component;
export declare const HeroiconsInformationCircleOutline: Component;
export declare const HeroiconsKeyOutline: Component;
export declare const HeroiconsLibraryOutline: Component;
export declare const HeroiconsLightBulbOutline: Component;
export declare const HeroiconsLightningBoltOutline: Component;
export declare const HeroiconsLinkOutline: Component;
export declare const HeroiconsLocationMarkerOutline: Component;
export declare const HeroiconsLockClosedOutline: Component;
export declare const HeroiconsLockOpenOutline: Component;
export declare const HeroiconsLogoutOutline: Component;
export declare const HeroiconsMailOpenOutline: Component;
export declare const HeroiconsMailOutline: Component;
export declare const HeroiconsMenuAlt1Outline: Component;
export declare const HeroiconsMenuAlt2Outline: Component;
export declare const HeroiconsMenuAlt3Outline: Component;
export declare const HeroiconsMenuAlt4Outline: Component;
export declare const HeroiconsMenuOutline: Component;
export declare const HeroiconsMicrophoneOutline: Component;
export declare const HeroiconsMinusCircleOutline: Component;
export declare const HeroiconsMoonOutline: Component;
export declare const HeroiconsNewspaperOutline: Component;
export declare const HeroiconsOfficeBuildingOutline: Component;
export declare const HeroiconsPaperClipOutline: Component;
export declare const HeroiconsPauseOutline: Component;
export declare const HeroiconsPencilAltOutline: Component;
export declare const HeroiconsPencilOutline: Component;
export declare const HeroiconsPhoneIncomingOutline: Component;
export declare const HeroiconsPhoneOutgoingOutline: Component;
export declare const HeroiconsPhoneOutline: Component;
export declare const HeroiconsPhotographOutline: Component;
export declare const HeroiconsPlayOutline: Component;
export declare const HeroiconsPlusCircleOutline: Component;
export declare const HeroiconsPlusOutline: Component;
export declare const HeroiconsPrinterOutline: Component;
export declare const HeroiconsQrcodeOutline: Component;
export declare const HeroiconsQuestionMarkCircleOutline: Component;
export declare const HeroiconsReceiptRefundOutline: Component;
export declare const HeroiconsRefreshOutline: Component;
export declare const HeroiconsReplyOutline: Component;
export declare const HeroiconsScaleOutline: Component;
export declare const HeroiconsSearchOutline: Component;
export declare const HeroiconsSelectorOutline: Component;
export declare const HeroiconsShareOutline: Component;
export declare const HeroiconsShieldCheckOutline: Component;
export declare const HeroiconsShieldExclamationOutline: Component;
export declare const HeroiconsShoppingCartOutline: Component;
export declare const HeroiconsSortAscendingOutline: Component;
export declare const HeroiconsSortDescendingOutline: Component;
export declare const HeroiconsSparklesOutline: Component;
export declare const HeroiconsSpeakerphoneOutline: Component;
export declare const HeroiconsStarOutline: Component;
export declare const HeroiconsStopOutline: Component;
export declare const HeroiconsSunOutline: Component;
export declare const HeroiconsSupportOutline: Component;
export declare const HeroiconsSwitchHorizontalOutline: Component;
export declare const HeroiconsSwitchVerticalOutline: Component;
export declare const HeroiconsTagOutline: Component;
export declare const HeroiconsTemplateOutline: Component;
export declare const HeroiconsTerminalOutline: Component;
export declare const HeroiconsTicketOutline: Component;
export declare const HeroiconsTranslateOutline: Component;
export declare const HeroiconsTrashOutline: Component;
export declare const HeroiconsTrendingDownOutline: Component;
export declare const HeroiconsTrendingUpOutline: Component;
export declare const HeroiconsUploadOutline: Component;
export declare const HeroiconsUserAddOutline: Component;
export declare const HeroiconsUserCircleOutline: Component;
export declare const HeroiconsUserGroupOutline: Component;
export declare const HeroiconsUserRemoveOutline: Component;
export declare const HeroiconsUserOutline: Component;
export declare const HeroiconsUsersOutline: Component;
export declare const HeroiconsViewBoardsOutline: Component;
export declare const HeroiconsViewGridAddOutline: Component;
export declare const HeroiconsViewListOutline: Component;
export declare const HeroiconsVolumeOffOutline: Component;
export declare const HeroiconsVolumeUpOutline: Component;
export declare const HeroiconsXCircleOutline: Component;
export declare const HeroiconsXOutline: Component;
export declare const HeroiconsZoomInOutline: Component;
export declare const HeroiconsZoomOutOutline: Component;
export declare const HeroiconsAdjustmentsSolid: Component;
export declare const HeroiconsAnnotationSolid: Component;
export declare const HeroiconsArchiveSolid: Component;
export declare const HeroiconsArrowCircleDownSolid: Component;
export declare const HeroiconsArrowCircleLeftSolid: Component;
export declare const HeroiconsArrowCircleRightSolid: Component;
export declare const HeroiconsArrowCircleUpSolid: Component;
export declare const HeroiconsArrowDownSolid: Component;
export declare const HeroiconsArrowLeftSolid: Component;
export declare const HeroiconsArrowNarrowDownSolid: Component;
export declare const HeroiconsArrowNarrowLeftSolid: Component;
export declare const HeroiconsArrowNarrowRightSolid: Component;
export declare const HeroiconsArrowNarrowUpSolid: Component;
export declare const HeroiconsArrowRightSolid: Component;
export declare const HeroiconsArrowUpSolid: Component;
export declare const HeroiconsAtSymbolSolid: Component;
export declare const HeroiconsBadgeCheckSolid: Component;
export declare const HeroiconsBanSolid: Component;
export declare const HeroiconsBellSolid: Component;
export declare const HeroiconsBookOpenSolid: Component;
export declare const HeroiconsBookmarkAltSolid: Component;
export declare const HeroiconsBookmarkSolid: Component;
export declare const HeroiconsBriefcaseSolid: Component;
export declare const HeroiconsCalendarSolid: Component;
export declare const HeroiconsCameraSolid: Component;
export declare const HeroiconsCashSolid: Component;
export declare const HeroiconsChartBarSolid: Component;
export declare const HeroiconsChartPieSolid: Component;
export declare const HeroiconsChartSquareBarSolid: Component;
export declare const HeroiconsChatAlt2Solid: Component;
export declare const HeroiconsChatAltSolid: Component;
export declare const HeroiconsChatSolid: Component;
export declare const HeroiconsCheckCircleSolid: Component;
export declare const HeroiconsCheckSolid: Component;
export declare const HeroiconsChevronDownSolid: Component;
export declare const HeroiconsChevronLeftSolid: Component;
export declare const HeroiconsChevronRightSolid: Component;
export declare const HeroiconsChevronUpSolid: Component;
export declare const HeroiconsClipboardCheckSolid: Component;
export declare const HeroiconsClipboardCopySolid: Component;
export declare const HeroiconsClipboardListSolid: Component;
export declare const HeroiconsClipboardSolid: Component;
export declare const HeroiconsClockSolid: Component;
export declare const HeroiconsCloudDownloadSolid: Component;
export declare const HeroiconsCloudUploadSolid: Component;
export declare const HeroiconsCodeSolid: Component;
export declare const HeroiconsCogSolid: Component;
export declare const HeroiconsCollectionSolid: Component;
export declare const HeroiconsColorSwatchSolid: Component;
export declare const HeroiconsCreditCardSolid: Component;
export declare const HeroiconsCurrencyDollarSolid: Component;
export declare const HeroiconsCurrencyEuroSolid: Component;
export declare const HeroiconsCurrencyPoundSolid: Component;
export declare const HeroiconsCurrencyRupeeSolid: Component;
export declare const HeroiconsCurrencyYenSolid: Component;
export declare const HeroiconsCursorClickSolid: Component;
export declare const HeroiconsDesktopComputerSolid: Component;
export declare const HeroiconsDocumentAddSolid: Component;
export declare const HeroiconsDocumentDownloadSolid: Component;
export declare const HeroiconsDocumentDuplicateSolid: Component;
export declare const HeroiconsDocumentRemoveSolid: Component;
export declare const HeroiconsDocumentReportSolid: Component;
export declare const HeroiconsDocumentSolid: Component;
export declare const HeroiconsDotsCircleHorizontalSolid: Component;
export declare const HeroiconsDotsHorizontalSolid: Component;
export declare const HeroiconsDotsVerticalSolid: Component;
export declare const HeroiconsDownloadSolid: Component;
export declare const HeroiconsDuplicateSolid: Component;
export declare const HeroiconsEmojiHappySolid: Component;
export declare const HeroiconsEmojiSadSolid: Component;
export declare const HeroiconsExclamationCircleSolid: Component;
export declare const HeroiconsExclamationSolid: Component;
export declare const HeroiconsExternalLinkSolid: Component;
export declare const HeroiconsEyeOffSolid: Component;
export declare const HeroiconsEyeSolid: Component;
export declare const HeroiconsFilterSolid: Component;
export declare const HeroiconsFlagSolid: Component;
export declare const HeroiconsFolderSolid: Component;
export declare const HeroiconsGlobeAltSolid: Component;
export declare const HeroiconsGlobeSolid: Component;
export declare const HeroiconsHashtagSolid: Component;
export declare const HeroiconsHeartSolid: Component;
export declare const HeroiconsHomeSolid: Component;
export declare const HeroiconsInboxInSolid: Component;
export declare const HeroiconsInboxSolid: Component;
export declare const HeroiconsInformationCircleSolid: Component;
export declare const HeroiconsKeySolid: Component;
export declare const HeroiconsLibrarySolid: Component;
export declare const HeroiconsLightBulbSolid: Component;
export declare const HeroiconsLightningBoltSolid: Component;
export declare const HeroiconsLinkSolid: Component;
export declare const HeroiconsLocationMarkerSolid: Component;
export declare const HeroiconsLockClosedSolid: Component;
export declare const HeroiconsLockOpenSolid: Component;
export declare const HeroiconsLogoutSolid: Component;
export declare const HeroiconsMailOpenSolid: Component;
export declare const HeroiconsMailSolid: Component;
export declare const HeroiconsMenuAlt1Solid: Component;
export declare const HeroiconsMenuAlt2Solid: Component;
export declare const HeroiconsMenuAlt3Solid: Component;
export declare const HeroiconsMenuAlt4Solid: Component;
export declare const HeroiconsMenuSolid: Component;
export declare const HeroiconsMicrophoneSolid: Component;
export declare const HeroiconsMinusCircleSolid: Component;
export declare const HeroiconsMoonSolid: Component;
export declare const HeroiconsNewspaperSolid: Component;
export declare const HeroiconsOfficeBuildingSolid: Component;
export declare const HeroiconsPaperClipSolid: Component;
export declare const HeroiconsPauseSolid: Component;
export declare const HeroiconsPencilAltSolid: Component;
export declare const HeroiconsPencilSolid: Component;
export declare const HeroiconsPhoneIncomingSolid: Component;
export declare const HeroiconsPhoneOutgoingSolid: Component;
export declare const HeroiconsPhoneSolid: Component;
export declare const HeroiconsPhotographSolid: Component;
export declare const HeroiconsPlaySolid: Component;
export declare const HeroiconsPlusCircleSolid: Component;
export declare const HeroiconsPlusSolid: Component;
export declare const HeroiconsPrinterSolid: Component;
export declare const HeroiconsQrcodeSolid: Component;
export declare const HeroiconsQuestionMarkCircleSolid: Component;
export declare const HeroiconsReceiptRefundSolid: Component;
export declare const HeroiconsRefreshSolid: Component;
export declare const HeroiconsReplySolid: Component;
export declare const HeroiconsScaleSolid: Component;
export declare const HeroiconsSearchSolid: Component;
export declare const HeroiconsSelectorSolid: Component;
export declare const HeroiconsShareSolid: Component;
export declare const HeroiconsShieldCheckSolid: Component;
export declare const HeroiconsShieldExclamationSolid: Component;
export declare const HeroiconsShoppingCartSolid: Component;
export declare const HeroiconsSortAscendingSolid: Component;
export declare const HeroiconsSortDescendingSolid: Component;
export declare const HeroiconsSparklesSolid: Component;
export declare const HeroiconsSpeakerphoneSolid: Component;
export declare const HeroiconsStarSolid: Component;
export declare const HeroiconsStopSolid: Component;
export declare const HeroiconsSunSolid: Component;
export declare const HeroiconsSupportSolid: Component;
export declare const HeroiconsSwitchHorizontalSolid: Component;
export declare const HeroiconsSwitchVerticalSolid: Component;
export declare const HeroiconsTagSolid: Component;
export declare const HeroiconsTemplateSolid: Component;
export declare const HeroiconsTerminalSolid: Component;
export declare const HeroiconsTicketSolid: Component;
export declare const HeroiconsTranslateSolid: Component;
export declare const HeroiconsTrashSolid: Component;
export declare const HeroiconsTrendingDownSolid: Component;
export declare const HeroiconsTrendingUpSolid: Component;
export declare const HeroiconsUploadSolid: Component;
export declare const HeroiconsUserAddSolid: Component;
export declare const HeroiconsUserCircleSolid: Component;
export declare const HeroiconsUserGroupSolid: Component;
export declare const HeroiconsUserRemoveSolid: Component;
export declare const HeroiconsUserSolid: Component;
export declare const HeroiconsUsersSolid: Component;
export declare const HeroiconsViewBoardsSolid: Component;
export declare const HeroiconsViewGridAddSolid: Component;
export declare const HeroiconsViewListSolid: Component;
export declare const HeroiconsVolumeOffSolid: Component;
export declare const HeroiconsVolumeUpSolid: Component;
export declare const HeroiconsXCircleSolid: Component;
export declare const HeroiconsXSolid: Component;
export declare const HeroiconsZoomInSolid: Component;
export declare const HeroiconsZoomOutSolid: Component;

export interface HeroiconsComponents {
  HeroiconsAdjustmentsOutline: Component;
  HeroiconsAnnotationOutline: Component;
  HeroiconsArchiveOutline: Component;
  HeroiconsArrowCircleDownOutline: Component;
  HeroiconsArrowCircleLeftOutline: Component;
  HeroiconsArrowCircleRightOutline: Component;
  HeroiconsArrowCircleUpOutline: Component;
  HeroiconsArrowDownOutline: Component;
  HeroiconsArrowLeftOutline: Component;
  HeroiconsArrowNarrowDownOutline: Component;
  HeroiconsArrowNarrowLeftOutline: Component;
  HeroiconsArrowNarrowRightOutline: Component;
  HeroiconsArrowNarrowUpOutline: Component;
  HeroiconsArrowRightOutline: Component;
  HeroiconsArrowUpOutline: Component;
  HeroiconsAtSymbolOutline: Component;
  HeroiconsBadgeCheckOutline: Component;
  HeroiconsBanOutline: Component;
  HeroiconsBellOutline: Component;
  HeroiconsBookOpenOutline: Component;
  HeroiconsBookmarkAltOutline: Component;
  HeroiconsBookmarkOutline: Component;
  HeroiconsBriefcaseOutline: Component;
  HeroiconsCalendarOutline: Component;
  HeroiconsCameraOutline: Component;
  HeroiconsCashOutline: Component;
  HeroiconsChartBarOutline: Component;
  HeroiconsChartPieOutline: Component;
  HeroiconsChartSquareBarOutline: Component;
  HeroiconsChatAlt2Outline: Component;
  HeroiconsChatAltOutline: Component;
  HeroiconsChatOutline: Component;
  HeroiconsCheckCircleOutline: Component;
  HeroiconsCheckOutline: Component;
  HeroiconsChevronDownOutline: Component;
  HeroiconsChevronLeftOutline: Component;
  HeroiconsChevronRightOutline: Component;
  HeroiconsChevronUpOutline: Component;
  HeroiconsClipboardCheckOutline: Component;
  HeroiconsClipboardCopyOutline: Component;
  HeroiconsClipboardListOutline: Component;
  HeroiconsClipboardOutline: Component;
  HeroiconsClockOutline: Component;
  HeroiconsCloudDownloadOutline: Component;
  HeroiconsCloudUploadOutline: Component;
  HeroiconsCodeOutline: Component;
  HeroiconsCogOutline: Component;
  HeroiconsCollectionOutline: Component;
  HeroiconsColorSwatchOutline: Component;
  HeroiconsCreditCardOutline: Component;
  HeroiconsCurrencyDollarOutline: Component;
  HeroiconsCurrencyEuroOutline: Component;
  HeroiconsCurrencyPoundOutline: Component;
  HeroiconsCurrencyRupeeOutline: Component;
  HeroiconsCurrencyYenOutline: Component;
  HeroiconsCursorClickOutline: Component;
  HeroiconsDesktopComputerOutline: Component;
  HeroiconsDocumentAddOutline: Component;
  HeroiconsDocumentDownloadOutline: Component;
  HeroiconsDocumentDuplicateOutline: Component;
  HeroiconsDocumentRemoveOutline: Component;
  HeroiconsDocumentReportOutline: Component;
  HeroiconsDocumentOutline: Component;
  HeroiconsDotsCircleHorizontalOutline: Component;
  HeroiconsDotsHorizontalOutline: Component;
  HeroiconsDotsVerticalOutline: Component;
  HeroiconsDownloadOutline: Component;
  HeroiconsDuplicateOutline: Component;
  HeroiconsEmojiHappyOutline: Component;
  HeroiconsEmojiSadOutline: Component;
  HeroiconsExclamationCircleOutline: Component;
  HeroiconsExclamationOutline: Component;
  HeroiconsExternalLinkOutline: Component;
  HeroiconsEyeOffOutline: Component;
  HeroiconsEyeOutline: Component;
  HeroiconsFilterOutline: Component;
  HeroiconsFlagOutline: Component;
  HeroiconsFolderOutline: Component;
  HeroiconsGlobeAltOutline: Component;
  HeroiconsGlobeOutline: Component;
  HeroiconsHashtagOutline: Component;
  HeroiconsHeartOutline: Component;
  HeroiconsHomeOutline: Component;
  HeroiconsInboxInOutline: Component;
  HeroiconsInboxOutline: Component;
  HeroiconsInformationCircleOutline: Component;
  HeroiconsKeyOutline: Component;
  HeroiconsLibraryOutline: Component;
  HeroiconsLightBulbOutline: Component;
  HeroiconsLightningBoltOutline: Component;
  HeroiconsLinkOutline: Component;
  HeroiconsLocationMarkerOutline: Component;
  HeroiconsLockClosedOutline: Component;
  HeroiconsLockOpenOutline: Component;
  HeroiconsLogoutOutline: Component;
  HeroiconsMailOpenOutline: Component;
  HeroiconsMailOutline: Component;
  HeroiconsMenuAlt1Outline: Component;
  HeroiconsMenuAlt2Outline: Component;
  HeroiconsMenuAlt3Outline: Component;
  HeroiconsMenuAlt4Outline: Component;
  HeroiconsMenuOutline: Component;
  HeroiconsMicrophoneOutline: Component;
  HeroiconsMinusCircleOutline: Component;
  HeroiconsMoonOutline: Component;
  HeroiconsNewspaperOutline: Component;
  HeroiconsOfficeBuildingOutline: Component;
  HeroiconsPaperClipOutline: Component;
  HeroiconsPauseOutline: Component;
  HeroiconsPencilAltOutline: Component;
  HeroiconsPencilOutline: Component;
  HeroiconsPhoneIncomingOutline: Component;
  HeroiconsPhoneOutgoingOutline: Component;
  HeroiconsPhoneOutline: Component;
  HeroiconsPhotographOutline: Component;
  HeroiconsPlayOutline: Component;
  HeroiconsPlusCircleOutline: Component;
  HeroiconsPlusOutline: Component;
  HeroiconsPrinterOutline: Component;
  HeroiconsQrcodeOutline: Component;
  HeroiconsQuestionMarkCircleOutline: Component;
  HeroiconsReceiptRefundOutline: Component;
  HeroiconsRefreshOutline: Component;
  HeroiconsReplyOutline: Component;
  HeroiconsScaleOutline: Component;
  HeroiconsSearchOutline: Component;
  HeroiconsSelectorOutline: Component;
  HeroiconsShareOutline: Component;
  HeroiconsShieldCheckOutline: Component;
  HeroiconsShieldExclamationOutline: Component;
  HeroiconsShoppingCartOutline: Component;
  HeroiconsSortAscendingOutline: Component;
  HeroiconsSortDescendingOutline: Component;
  HeroiconsSparklesOutline: Component;
  HeroiconsSpeakerphoneOutline: Component;
  HeroiconsStarOutline: Component;
  HeroiconsStopOutline: Component;
  HeroiconsSunOutline: Component;
  HeroiconsSupportOutline: Component;
  HeroiconsSwitchHorizontalOutline: Component;
  HeroiconsSwitchVerticalOutline: Component;
  HeroiconsTagOutline: Component;
  HeroiconsTemplateOutline: Component;
  HeroiconsTerminalOutline: Component;
  HeroiconsTicketOutline: Component;
  HeroiconsTranslateOutline: Component;
  HeroiconsTrashOutline: Component;
  HeroiconsTrendingDownOutline: Component;
  HeroiconsTrendingUpOutline: Component;
  HeroiconsUploadOutline: Component;
  HeroiconsUserAddOutline: Component;
  HeroiconsUserCircleOutline: Component;
  HeroiconsUserGroupOutline: Component;
  HeroiconsUserRemoveOutline: Component;
  HeroiconsUserOutline: Component;
  HeroiconsUsersOutline: Component;
  HeroiconsViewBoardsOutline: Component;
  HeroiconsViewGridAddOutline: Component;
  HeroiconsViewListOutline: Component;
  HeroiconsVolumeOffOutline: Component;
  HeroiconsVolumeUpOutline: Component;
  HeroiconsXCircleOutline: Component;
  HeroiconsXOutline: Component;
  HeroiconsZoomInOutline: Component;
  HeroiconsZoomOutOutline: Component;
  HeroiconsAdjustmentsSolid: Component;
  HeroiconsAnnotationSolid: Component;
  HeroiconsArchiveSolid: Component;
  HeroiconsArrowCircleDownSolid: Component;
  HeroiconsArrowCircleLeftSolid: Component;
  HeroiconsArrowCircleRightSolid: Component;
  HeroiconsArrowCircleUpSolid: Component;
  HeroiconsArrowDownSolid: Component;
  HeroiconsArrowLeftSolid: Component;
  HeroiconsArrowNarrowDownSolid: Component;
  HeroiconsArrowNarrowLeftSolid: Component;
  HeroiconsArrowNarrowRightSolid: Component;
  HeroiconsArrowNarrowUpSolid: Component;
  HeroiconsArrowRightSolid: Component;
  HeroiconsArrowUpSolid: Component;
  HeroiconsAtSymbolSolid: Component;
  HeroiconsBadgeCheckSolid: Component;
  HeroiconsBanSolid: Component;
  HeroiconsBellSolid: Component;
  HeroiconsBookOpenSolid: Component;
  HeroiconsBookmarkAltSolid: Component;
  HeroiconsBookmarkSolid: Component;
  HeroiconsBriefcaseSolid: Component;
  HeroiconsCalendarSolid: Component;
  HeroiconsCameraSolid: Component;
  HeroiconsCashSolid: Component;
  HeroiconsChartBarSolid: Component;
  HeroiconsChartPieSolid: Component;
  HeroiconsChartSquareBarSolid: Component;
  HeroiconsChatAlt2Solid: Component;
  HeroiconsChatAltSolid: Component;
  HeroiconsChatSolid: Component;
  HeroiconsCheckCircleSolid: Component;
  HeroiconsCheckSolid: Component;
  HeroiconsChevronDownSolid: Component;
  HeroiconsChevronLeftSolid: Component;
  HeroiconsChevronRightSolid: Component;
  HeroiconsChevronUpSolid: Component;
  HeroiconsClipboardCheckSolid: Component;
  HeroiconsClipboardCopySolid: Component;
  HeroiconsClipboardListSolid: Component;
  HeroiconsClipboardSolid: Component;
  HeroiconsClockSolid: Component;
  HeroiconsCloudDownloadSolid: Component;
  HeroiconsCloudUploadSolid: Component;
  HeroiconsCodeSolid: Component;
  HeroiconsCogSolid: Component;
  HeroiconsCollectionSolid: Component;
  HeroiconsColorSwatchSolid: Component;
  HeroiconsCreditCardSolid: Component;
  HeroiconsCurrencyDollarSolid: Component;
  HeroiconsCurrencyEuroSolid: Component;
  HeroiconsCurrencyPoundSolid: Component;
  HeroiconsCurrencyRupeeSolid: Component;
  HeroiconsCurrencyYenSolid: Component;
  HeroiconsCursorClickSolid: Component;
  HeroiconsDesktopComputerSolid: Component;
  HeroiconsDocumentAddSolid: Component;
  HeroiconsDocumentDownloadSolid: Component;
  HeroiconsDocumentDuplicateSolid: Component;
  HeroiconsDocumentRemoveSolid: Component;
  HeroiconsDocumentReportSolid: Component;
  HeroiconsDocumentSolid: Component;
  HeroiconsDotsCircleHorizontalSolid: Component;
  HeroiconsDotsHorizontalSolid: Component;
  HeroiconsDotsVerticalSolid: Component;
  HeroiconsDownloadSolid: Component;
  HeroiconsDuplicateSolid: Component;
  HeroiconsEmojiHappySolid: Component;
  HeroiconsEmojiSadSolid: Component;
  HeroiconsExclamationCircleSolid: Component;
  HeroiconsExclamationSolid: Component;
  HeroiconsExternalLinkSolid: Component;
  HeroiconsEyeOffSolid: Component;
  HeroiconsEyeSolid: Component;
  HeroiconsFilterSolid: Component;
  HeroiconsFlagSolid: Component;
  HeroiconsFolderSolid: Component;
  HeroiconsGlobeAltSolid: Component;
  HeroiconsGlobeSolid: Component;
  HeroiconsHashtagSolid: Component;
  HeroiconsHeartSolid: Component;
  HeroiconsHomeSolid: Component;
  HeroiconsInboxInSolid: Component;
  HeroiconsInboxSolid: Component;
  HeroiconsInformationCircleSolid: Component;
  HeroiconsKeySolid: Component;
  HeroiconsLibrarySolid: Component;
  HeroiconsLightBulbSolid: Component;
  HeroiconsLightningBoltSolid: Component;
  HeroiconsLinkSolid: Component;
  HeroiconsLocationMarkerSolid: Component;
  HeroiconsLockClosedSolid: Component;
  HeroiconsLockOpenSolid: Component;
  HeroiconsLogoutSolid: Component;
  HeroiconsMailOpenSolid: Component;
  HeroiconsMailSolid: Component;
  HeroiconsMenuAlt1Solid: Component;
  HeroiconsMenuAlt2Solid: Component;
  HeroiconsMenuAlt3Solid: Component;
  HeroiconsMenuAlt4Solid: Component;
  HeroiconsMenuSolid: Component;
  HeroiconsMicrophoneSolid: Component;
  HeroiconsMinusCircleSolid: Component;
  HeroiconsMoonSolid: Component;
  HeroiconsNewspaperSolid: Component;
  HeroiconsOfficeBuildingSolid: Component;
  HeroiconsPaperClipSolid: Component;
  HeroiconsPauseSolid: Component;
  HeroiconsPencilAltSolid: Component;
  HeroiconsPencilSolid: Component;
  HeroiconsPhoneIncomingSolid: Component;
  HeroiconsPhoneOutgoingSolid: Component;
  HeroiconsPhoneSolid: Component;
  HeroiconsPhotographSolid: Component;
  HeroiconsPlaySolid: Component;
  HeroiconsPlusCircleSolid: Component;
  HeroiconsPlusSolid: Component;
  HeroiconsPrinterSolid: Component;
  HeroiconsQrcodeSolid: Component;
  HeroiconsQuestionMarkCircleSolid: Component;
  HeroiconsReceiptRefundSolid: Component;
  HeroiconsRefreshSolid: Component;
  HeroiconsReplySolid: Component;
  HeroiconsScaleSolid: Component;
  HeroiconsSearchSolid: Component;
  HeroiconsSelectorSolid: Component;
  HeroiconsShareSolid: Component;
  HeroiconsShieldCheckSolid: Component;
  HeroiconsShieldExclamationSolid: Component;
  HeroiconsShoppingCartSolid: Component;
  HeroiconsSortAscendingSolid: Component;
  HeroiconsSortDescendingSolid: Component;
  HeroiconsSparklesSolid: Component;
  HeroiconsSpeakerphoneSolid: Component;
  HeroiconsStarSolid: Component;
  HeroiconsStopSolid: Component;
  HeroiconsSunSolid: Component;
  HeroiconsSupportSolid: Component;
  HeroiconsSwitchHorizontalSolid: Component;
  HeroiconsSwitchVerticalSolid: Component;
  HeroiconsTagSolid: Component;
  HeroiconsTemplateSolid: Component;
  HeroiconsTerminalSolid: Component;
  HeroiconsTicketSolid: Component;
  HeroiconsTranslateSolid: Component;
  HeroiconsTrashSolid: Component;
  HeroiconsTrendingDownSolid: Component;
  HeroiconsTrendingUpSolid: Component;
  HeroiconsUploadSolid: Component;
  HeroiconsUserAddSolid: Component;
  HeroiconsUserCircleSolid: Component;
  HeroiconsUserGroupSolid: Component;
  HeroiconsUserRemoveSolid: Component;
  HeroiconsUserSolid: Component;
  HeroiconsUsersSolid: Component;
  HeroiconsViewBoardsSolid: Component;
  HeroiconsViewGridAddSolid: Component;
  HeroiconsViewListSolid: Component;
  HeroiconsVolumeOffSolid: Component;
  HeroiconsVolumeUpSolid: Component;
  HeroiconsXCircleSolid: Component;
  HeroiconsXSolid: Component;
  HeroiconsZoomInSolid: Component;
  HeroiconsZoomOutSolid: Component;
  [key: string]: Component;
}

type VueHeroiconsInstaller = PluginFunction<HeroiconsPluginOptions>;

export interface Heroicons {
  install: VueHeroiconsInstaller;
  icons: HeroiconsComponents;
}

export declare const icons: HeroiconsComponents;

export declare const Heroicons: Heroicons;

export default Heroicons;
    