import { PluginFunction, Component } from 'vue';
import { HeroiconsPluginOptions } from './lib';

export { HeroiconsPluginOptions } from './lib';

export type HeroiconsAdjustmentsOutline = Component;
export type HeroiconsAnnotationOutline = Component;
export type HeroiconsArchiveOutline = Component;
export type HeroiconsArrowCircleDownOutline = Component;
export type HeroiconsArrowCircleLeftOutline = Component;
export type HeroiconsArrowCircleRightOutline = Component;
export type HeroiconsArrowCircleUpOutline = Component;
export type HeroiconsArrowDownOutline = Component;
export type HeroiconsArrowLeftOutline = Component;
export type HeroiconsArrowNarrowDownOutline = Component;
export type HeroiconsArrowNarrowLeftOutline = Component;
export type HeroiconsArrowNarrowRightOutline = Component;
export type HeroiconsArrowNarrowUpOutline = Component;
export type HeroiconsArrowRightOutline = Component;
export type HeroiconsArrowUpOutline = Component;
export type HeroiconsAtSymbolOutline = Component;
export type HeroiconsBadgeCheckOutline = Component;
export type HeroiconsBanOutline = Component;
export type HeroiconsBellOutline = Component;
export type HeroiconsBookOpenOutline = Component;
export type HeroiconsBookmarkAltOutline = Component;
export type HeroiconsBookmarkOutline = Component;
export type HeroiconsBriefcaseOutline = Component;
export type HeroiconsCalendarOutline = Component;
export type HeroiconsCameraOutline = Component;
export type HeroiconsCashOutline = Component;
export type HeroiconsChartBarOutline = Component;
export type HeroiconsChartPieOutline = Component;
export type HeroiconsChartSquareBarOutline = Component;
export type HeroiconsChatAlt2Outline = Component;
export type HeroiconsChatAltOutline = Component;
export type HeroiconsChatOutline = Component;
export type HeroiconsCheckCircleOutline = Component;
export type HeroiconsCheckOutline = Component;
export type HeroiconsCheveronDownOutline = Component;
export type HeroiconsCheveronLeftOutline = Component;
export type HeroiconsCheveronRightOutline = Component;
export type HeroiconsCheveronUpOutline = Component;
export type HeroiconsClipboardCheckOutline = Component;
export type HeroiconsClipboardCopyOutline = Component;
export type HeroiconsClipboardListOutline = Component;
export type HeroiconsClipboardOutline = Component;
export type HeroiconsClockOutline = Component;
export type HeroiconsCloudDownloadOutline = Component;
export type HeroiconsCloudUploadOutline = Component;
export type HeroiconsCodeOutline = Component;
export type HeroiconsCogOutline = Component;
export type HeroiconsCollectionOutline = Component;
export type HeroiconsColorSwatchOutline = Component;
export type HeroiconsCreditCardOutline = Component;
export type HeroiconsCurrencyDollarOutline = Component;
export type HeroiconsCurrencyEuroOutline = Component;
export type HeroiconsCurrencyPoundOutline = Component;
export type HeroiconsCurrencyRupeeOutline = Component;
export type HeroiconsCurrencyYenOutline = Component;
export type HeroiconsCursorClickOutline = Component;
export type HeroiconsDesktopComputerOutline = Component;
export type HeroiconsDocumentAddOutline = Component;
export type HeroiconsDocumentDownloadOutline = Component;
export type HeroiconsDocumentDuplicateOutline = Component;
export type HeroiconsDocumentRemoveOutline = Component;
export type HeroiconsDocumentReportOutline = Component;
export type HeroiconsDocumentOutline = Component;
export type HeroiconsDotsCircleHorizontalOutline = Component;
export type HeroiconsDotsHorizontalOutline = Component;
export type HeroiconsDotsVerticalOutline = Component;
export type HeroiconsDownloadOutline = Component;
export type HeroiconsDuplicateOutline = Component;
export type HeroiconsEmojiHappyOutline = Component;
export type HeroiconsEmojiSadOutline = Component;
export type HeroiconsExclamationCircleOutline = Component;
export type HeroiconsExclamationOutline = Component;
export type HeroiconsExternalLinkOutline = Component;
export type HeroiconsEyeOffOutline = Component;
export type HeroiconsEyeOutline = Component;
export type HeroiconsFilterOutline = Component;
export type HeroiconsFlagOutline = Component;
export type HeroiconsFolderOutline = Component;
export type HeroiconsGlobeAltOutline = Component;
export type HeroiconsGlobeOutline = Component;
export type HeroiconsHashtagOutline = Component;
export type HeroiconsHeartOutline = Component;
export type HeroiconsHomeOutline = Component;
export type HeroiconsInboxInOutline = Component;
export type HeroiconsInboxOutline = Component;
export type HeroiconsInformationCircleOutline = Component;
export type HeroiconsKeyOutline = Component;
export type HeroiconsLibraryOutline = Component;
export type HeroiconsLightBulbOutline = Component;
export type HeroiconsLightningBoltOutline = Component;
export type HeroiconsLinkOutline = Component;
export type HeroiconsLocationMarkerOutline = Component;
export type HeroiconsLockClosedOutline = Component;
export type HeroiconsLockOpenOutline = Component;
export type HeroiconsLogoutOutline = Component;
export type HeroiconsMailOpenOutline = Component;
export type HeroiconsMailOutline = Component;
export type HeroiconsMenuAlt1Outline = Component;
export type HeroiconsMenuAlt2Outline = Component;
export type HeroiconsMenuAlt3Outline = Component;
export type HeroiconsMenuAlt4Outline = Component;
export type HeroiconsMenuOutline = Component;
export type HeroiconsMicrophoneOutline = Component;
export type HeroiconsMinusCircleOutline = Component;
export type HeroiconsMoonOutline = Component;
export type HeroiconsNewspaperOutline = Component;
export type HeroiconsOfficeBuildingOutline = Component;
export type HeroiconsPaperClipOutline = Component;
export type HeroiconsPauseOutline = Component;
export type HeroiconsPencilAltOutline = Component;
export type HeroiconsPencilOutline = Component;
export type HeroiconsPhoneIncomingOutline = Component;
export type HeroiconsPhoneOutgoingOutline = Component;
export type HeroiconsPhoneOutline = Component;
export type HeroiconsPhotographOutline = Component;
export type HeroiconsPlayOutline = Component;
export type HeroiconsPlusCircleOutline = Component;
export type HeroiconsPlusOutline = Component;
export type HeroiconsPrinterOutline = Component;
export type HeroiconsQrcodeOutline = Component;
export type HeroiconsQuestionMarkCircleOutline = Component;
export type HeroiconsReceiptRefundOutline = Component;
export type HeroiconsRefreshOutline = Component;
export type HeroiconsReplyOutline = Component;
export type HeroiconsScaleOutline = Component;
export type HeroiconsSearchOutline = Component;
export type HeroiconsSelectorOutline = Component;
export type HeroiconsShareOutline = Component;
export type HeroiconsShieldCheckOutline = Component;
export type HeroiconsShieldExclamationOutline = Component;
export type HeroiconsShoppingCartOutline = Component;
export type HeroiconsSortAscendingOutline = Component;
export type HeroiconsSortDescendingOutline = Component;
export type HeroiconsSparklesOutline = Component;
export type HeroiconsSpeakerphoneOutline = Component;
export type HeroiconsStarOutline = Component;
export type HeroiconsStopOutline = Component;
export type HeroiconsSunOutline = Component;
export type HeroiconsSupportOutline = Component;
export type HeroiconsSwitchHorizontalOutline = Component;
export type HeroiconsSwitchVerticalOutline = Component;
export type HeroiconsTagOutline = Component;
export type HeroiconsTemplateOutline = Component;
export type HeroiconsTerminalOutline = Component;
export type HeroiconsTicketOutline = Component;
export type HeroiconsTranslateOutline = Component;
export type HeroiconsTrashOutline = Component;
export type HeroiconsTrendingDownOutline = Component;
export type HeroiconsTrendingUpOutline = Component;
export type HeroiconsUploadOutline = Component;
export type HeroiconsUserAddOutline = Component;
export type HeroiconsUserCircleOutline = Component;
export type HeroiconsUserGroupOutline = Component;
export type HeroiconsUserRemoveOutline = Component;
export type HeroiconsUserOutline = Component;
export type HeroiconsUsersOutline = Component;
export type HeroiconsViewBoardsOutline = Component;
export type HeroiconsViewGridAddOutline = Component;
export type HeroiconsViewListOutline = Component;
export type HeroiconsVolumeOffOutline = Component;
export type HeroiconsVolumeUpOutline = Component;
export type HeroiconsXCircleOutline = Component;
export type HeroiconsXOutline = Component;
export type HeroiconsZoomInOutline = Component;
export type HeroiconsZoomOutOutline = Component;
export type HeroiconsLibrarySolid = Component;
export type HeroiconsAdjustmentsSolid = Component;
export type HeroiconsAnnotationSolid = Component;
export type HeroiconsArchiveSolid = Component;
export type HeroiconsArrowCircleDownSolid = Component;
export type HeroiconsArrowCircleLeftSolid = Component;
export type HeroiconsArrowCircleRightSolid = Component;
export type HeroiconsArrowCircleUpSolid = Component;
export type HeroiconsArrowDownSolid = Component;
export type HeroiconsArrowLeftSolid = Component;
export type HeroiconsArrowNarrowDownSolid = Component;
export type HeroiconsArrowNarrowLeftSolid = Component;
export type HeroiconsArrowNarrowRightSolid = Component;
export type HeroiconsArrowNarrowUpSolid = Component;
export type HeroiconsArrowRightSolid = Component;
export type HeroiconsArrowUpSolid = Component;
export type HeroiconsAtSymbolSolid = Component;
export type HeroiconsBadgeCheckSolid = Component;
export type HeroiconsBanSolid = Component;
export type HeroiconsBellSolid = Component;
export type HeroiconsBookOpenSolid = Component;
export type HeroiconsBookmarkAltSolid = Component;
export type HeroiconsBookmarkSolid = Component;
export type HeroiconsBriefcaseSolid = Component;
export type HeroiconsCalendarSolid = Component;
export type HeroiconsCameraSolid = Component;
export type HeroiconsCashSolid = Component;
export type HeroiconsChartBarSolid = Component;
export type HeroiconsChartPieSolid = Component;
export type HeroiconsChartSquareBarSolid = Component;
export type HeroiconsChatAlt2Solid = Component;
export type HeroiconsChatAltSolid = Component;
export type HeroiconsChatSolid = Component;
export type HeroiconsCheckCircleSolid = Component;
export type HeroiconsCheckSolid = Component;
export type HeroiconsCheveronDownSolid = Component;
export type HeroiconsCheveronLeftSolid = Component;
export type HeroiconsCheveronRightSolid = Component;
export type HeroiconsCheveronUpSolid = Component;
export type HeroiconsClipboardCheckSolid = Component;
export type HeroiconsClipboardCopySolid = Component;
export type HeroiconsClipboardListSolid = Component;
export type HeroiconsClipboardSolid = Component;
export type HeroiconsClockSolid = Component;
export type HeroiconsCloudDownloadSolid = Component;
export type HeroiconsCloudUploadSolid = Component;
export type HeroiconsCodeSolid = Component;
export type HeroiconsCogSolid = Component;
export type HeroiconsCollectionSolid = Component;
export type HeroiconsColorSwatchSolid = Component;
export type HeroiconsCreditCardSolid = Component;
export type HeroiconsCurrencyDollarSolid = Component;
export type HeroiconsCurrencyEuroSolid = Component;
export type HeroiconsCurrencyPoundSolid = Component;
export type HeroiconsCurrencyRupeeSolid = Component;
export type HeroiconsCurrencyYenSolid = Component;
export type HeroiconsCursorClickSolid = Component;
export type HeroiconsDesktopComputerSolid = Component;
export type HeroiconsDocumentAddSolid = Component;
export type HeroiconsDocumentDownloadSolid = Component;
export type HeroiconsDocumentDuplicateSolid = Component;
export type HeroiconsDocumentRemoveSolid = Component;
export type HeroiconsDocumentReportSolid = Component;
export type HeroiconsDocumentSolid = Component;
export type HeroiconsDotsCircleHorizontalSolid = Component;
export type HeroiconsDotsHorizontalSolid = Component;
export type HeroiconsDotsVerticalSolid = Component;
export type HeroiconsDownloadSolid = Component;
export type HeroiconsDuplicateSolid = Component;
export type HeroiconsEmojiHappySolid = Component;
export type HeroiconsEmojiSadSolid = Component;
export type HeroiconsExclamationCircleSolid = Component;
export type HeroiconsExclamationSolid = Component;
export type HeroiconsExternalLinkSolid = Component;
export type HeroiconsEyeOffSolid = Component;
export type HeroiconsEyeSolid = Component;
export type HeroiconsFilterSolid = Component;
export type HeroiconsFlagSolid = Component;
export type HeroiconsFolderSolid = Component;
export type HeroiconsGlobeAltSolid = Component;
export type HeroiconsGlobeSolid = Component;
export type HeroiconsHashtagSolid = Component;
export type HeroiconsHeartSolid = Component;
export type HeroiconsHomeSolid = Component;
export type HeroiconsInboxInSolid = Component;
export type HeroiconsInboxSolid = Component;
export type HeroiconsInformationCircleSolid = Component;
export type HeroiconsKeySolid = Component;
export type HeroiconsLightBulbSolid = Component;
export type HeroiconsLightningBoltSolid = Component;
export type HeroiconsLinkSolid = Component;
export type HeroiconsLocationMarkerSolid = Component;
export type HeroiconsLockClosedSolid = Component;
export type HeroiconsLockOpenSolid = Component;
export type HeroiconsLogoutSolid = Component;
export type HeroiconsMailOpenSolid = Component;
export type HeroiconsMailSolid = Component;
export type HeroiconsMenuAlt1Solid = Component;
export type HeroiconsMenuAlt2Solid = Component;
export type HeroiconsMenuAlt3Solid = Component;
export type HeroiconsMenuAlt4Solid = Component;
export type HeroiconsMenuSolid = Component;
export type HeroiconsMicrophoneSolid = Component;
export type HeroiconsMinusCircleSolid = Component;
export type HeroiconsMoonSolid = Component;
export type HeroiconsNewspaperSolid = Component;
export type HeroiconsOfficeBuildingSolid = Component;
export type HeroiconsPaperClipSolid = Component;
export type HeroiconsPauseSolid = Component;
export type HeroiconsPencilAltSolid = Component;
export type HeroiconsPencilSolid = Component;
export type HeroiconsPhoneIncomingSolid = Component;
export type HeroiconsPhoneOutgoingSolid = Component;
export type HeroiconsPhoneSolid = Component;
export type HeroiconsPhotographSolid = Component;
export type HeroiconsPlaySolid = Component;
export type HeroiconsPlusCircleSolid = Component;
export type HeroiconsPlusSolid = Component;
export type HeroiconsPrinterSolid = Component;
export type HeroiconsQrcodeSolid = Component;
export type HeroiconsQuestionMarkCircleSolid = Component;
export type HeroiconsReceiptRefundSolid = Component;
export type HeroiconsRefreshSolid = Component;
export type HeroiconsReplySolid = Component;
export type HeroiconsScaleSolid = Component;
export type HeroiconsSearchSolid = Component;
export type HeroiconsSelectorSolid = Component;
export type HeroiconsShareSolid = Component;
export type HeroiconsShieldCheckSolid = Component;
export type HeroiconsShieldExclamationSolid = Component;
export type HeroiconsShoppingCartSolid = Component;
export type HeroiconsSortAscendingSolid = Component;
export type HeroiconsSortDescendingSolid = Component;
export type HeroiconsSparklesSolid = Component;
export type HeroiconsSpeakerphoneSolid = Component;
export type HeroiconsStarSolid = Component;
export type HeroiconsStopSolid = Component;
export type HeroiconsSunSolid = Component;
export type HeroiconsSupportSolid = Component;
export type HeroiconsSwitchHorizontalSolid = Component;
export type HeroiconsSwitchVerticalSolid = Component;
export type HeroiconsTagSolid = Component;
export type HeroiconsTemplateSolid = Component;
export type HeroiconsTerminalSolid = Component;
export type HeroiconsTicketSolid = Component;
export type HeroiconsTranslateSolid = Component;
export type HeroiconsTrashSolid = Component;
export type HeroiconsTrendingDownSolid = Component;
export type HeroiconsTrendingUpSolid = Component;
export type HeroiconsUploadSolid = Component;
export type HeroiconsUserAddSolid = Component;
export type HeroiconsUserCircleSolid = Component;
export type HeroiconsUserGroupSolid = Component;
export type HeroiconsUserRemoveSolid = Component;
export type HeroiconsUserSolid = Component;
export type HeroiconsUsersSolid = Component;
export type HeroiconsViewBoardsSolid = Component;
export type HeroiconsViewGridAddSolid = Component;
export type HeroiconsViewListSolid = Component;
export type HeroiconsVolumeOffSolid = Component;
export type HeroiconsVolumeUpSolid = Component;
export type HeroiconsXCircleSolid = Component;
export type HeroiconsXSolid = Component;
export type HeroiconsZoomInSolid = Component;
export type HeroiconsZoomOutSolid = Component;

export interface HeroiconsComponents {
  HeroiconsAdjustmentsOutline: HeroiconsAdjustmentsOutline;
  HeroiconsAnnotationOutline: HeroiconsAnnotationOutline;
  HeroiconsArchiveOutline: HeroiconsArchiveOutline;
  HeroiconsArrowCircleDownOutline: HeroiconsArrowCircleDownOutline;
  HeroiconsArrowCircleLeftOutline: HeroiconsArrowCircleLeftOutline;
  HeroiconsArrowCircleRightOutline: HeroiconsArrowCircleRightOutline;
  HeroiconsArrowCircleUpOutline: HeroiconsArrowCircleUpOutline;
  HeroiconsArrowDownOutline: HeroiconsArrowDownOutline;
  HeroiconsArrowLeftOutline: HeroiconsArrowLeftOutline;
  HeroiconsArrowNarrowDownOutline: HeroiconsArrowNarrowDownOutline;
  HeroiconsArrowNarrowLeftOutline: HeroiconsArrowNarrowLeftOutline;
  HeroiconsArrowNarrowRightOutline: HeroiconsArrowNarrowRightOutline;
  HeroiconsArrowNarrowUpOutline: HeroiconsArrowNarrowUpOutline;
  HeroiconsArrowRightOutline: HeroiconsArrowRightOutline;
  HeroiconsArrowUpOutline: HeroiconsArrowUpOutline;
  HeroiconsAtSymbolOutline: HeroiconsAtSymbolOutline;
  HeroiconsBadgeCheckOutline: HeroiconsBadgeCheckOutline;
  HeroiconsBanOutline: HeroiconsBanOutline;
  HeroiconsBellOutline: HeroiconsBellOutline;
  HeroiconsBookOpenOutline: HeroiconsBookOpenOutline;
  HeroiconsBookmarkAltOutline: HeroiconsBookmarkAltOutline;
  HeroiconsBookmarkOutline: HeroiconsBookmarkOutline;
  HeroiconsBriefcaseOutline: HeroiconsBriefcaseOutline;
  HeroiconsCalendarOutline: HeroiconsCalendarOutline;
  HeroiconsCameraOutline: HeroiconsCameraOutline;
  HeroiconsCashOutline: HeroiconsCashOutline;
  HeroiconsChartBarOutline: HeroiconsChartBarOutline;
  HeroiconsChartPieOutline: HeroiconsChartPieOutline;
  HeroiconsChartSquareBarOutline: HeroiconsChartSquareBarOutline;
  HeroiconsChatAlt2Outline: HeroiconsChatAlt2Outline;
  HeroiconsChatAltOutline: HeroiconsChatAltOutline;
  HeroiconsChatOutline: HeroiconsChatOutline;
  HeroiconsCheckCircleOutline: HeroiconsCheckCircleOutline;
  HeroiconsCheckOutline: HeroiconsCheckOutline;
  HeroiconsCheveronDownOutline: HeroiconsCheveronDownOutline;
  HeroiconsCheveronLeftOutline: HeroiconsCheveronLeftOutline;
  HeroiconsCheveronRightOutline: HeroiconsCheveronRightOutline;
  HeroiconsCheveronUpOutline: HeroiconsCheveronUpOutline;
  HeroiconsClipboardCheckOutline: HeroiconsClipboardCheckOutline;
  HeroiconsClipboardCopyOutline: HeroiconsClipboardCopyOutline;
  HeroiconsClipboardListOutline: HeroiconsClipboardListOutline;
  HeroiconsClipboardOutline: HeroiconsClipboardOutline;
  HeroiconsClockOutline: HeroiconsClockOutline;
  HeroiconsCloudDownloadOutline: HeroiconsCloudDownloadOutline;
  HeroiconsCloudUploadOutline: HeroiconsCloudUploadOutline;
  HeroiconsCodeOutline: HeroiconsCodeOutline;
  HeroiconsCogOutline: HeroiconsCogOutline;
  HeroiconsCollectionOutline: HeroiconsCollectionOutline;
  HeroiconsColorSwatchOutline: HeroiconsColorSwatchOutline;
  HeroiconsCreditCardOutline: HeroiconsCreditCardOutline;
  HeroiconsCurrencyDollarOutline: HeroiconsCurrencyDollarOutline;
  HeroiconsCurrencyEuroOutline: HeroiconsCurrencyEuroOutline;
  HeroiconsCurrencyPoundOutline: HeroiconsCurrencyPoundOutline;
  HeroiconsCurrencyRupeeOutline: HeroiconsCurrencyRupeeOutline;
  HeroiconsCurrencyYenOutline: HeroiconsCurrencyYenOutline;
  HeroiconsCursorClickOutline: HeroiconsCursorClickOutline;
  HeroiconsDesktopComputerOutline: HeroiconsDesktopComputerOutline;
  HeroiconsDocumentAddOutline: HeroiconsDocumentAddOutline;
  HeroiconsDocumentDownloadOutline: HeroiconsDocumentDownloadOutline;
  HeroiconsDocumentDuplicateOutline: HeroiconsDocumentDuplicateOutline;
  HeroiconsDocumentRemoveOutline: HeroiconsDocumentRemoveOutline;
  HeroiconsDocumentReportOutline: HeroiconsDocumentReportOutline;
  HeroiconsDocumentOutline: HeroiconsDocumentOutline;
  HeroiconsDotsCircleHorizontalOutline: HeroiconsDotsCircleHorizontalOutline;
  HeroiconsDotsHorizontalOutline: HeroiconsDotsHorizontalOutline;
  HeroiconsDotsVerticalOutline: HeroiconsDotsVerticalOutline;
  HeroiconsDownloadOutline: HeroiconsDownloadOutline;
  HeroiconsDuplicateOutline: HeroiconsDuplicateOutline;
  HeroiconsEmojiHappyOutline: HeroiconsEmojiHappyOutline;
  HeroiconsEmojiSadOutline: HeroiconsEmojiSadOutline;
  HeroiconsExclamationCircleOutline: HeroiconsExclamationCircleOutline;
  HeroiconsExclamationOutline: HeroiconsExclamationOutline;
  HeroiconsExternalLinkOutline: HeroiconsExternalLinkOutline;
  HeroiconsEyeOffOutline: HeroiconsEyeOffOutline;
  HeroiconsEyeOutline: HeroiconsEyeOutline;
  HeroiconsFilterOutline: HeroiconsFilterOutline;
  HeroiconsFlagOutline: HeroiconsFlagOutline;
  HeroiconsFolderOutline: HeroiconsFolderOutline;
  HeroiconsGlobeAltOutline: HeroiconsGlobeAltOutline;
  HeroiconsGlobeOutline: HeroiconsGlobeOutline;
  HeroiconsHashtagOutline: HeroiconsHashtagOutline;
  HeroiconsHeartOutline: HeroiconsHeartOutline;
  HeroiconsHomeOutline: HeroiconsHomeOutline;
  HeroiconsInboxInOutline: HeroiconsInboxInOutline;
  HeroiconsInboxOutline: HeroiconsInboxOutline;
  HeroiconsInformationCircleOutline: HeroiconsInformationCircleOutline;
  HeroiconsKeyOutline: HeroiconsKeyOutline;
  HeroiconsLibraryOutline: HeroiconsLibraryOutline;
  HeroiconsLightBulbOutline: HeroiconsLightBulbOutline;
  HeroiconsLightningBoltOutline: HeroiconsLightningBoltOutline;
  HeroiconsLinkOutline: HeroiconsLinkOutline;
  HeroiconsLocationMarkerOutline: HeroiconsLocationMarkerOutline;
  HeroiconsLockClosedOutline: HeroiconsLockClosedOutline;
  HeroiconsLockOpenOutline: HeroiconsLockOpenOutline;
  HeroiconsLogoutOutline: HeroiconsLogoutOutline;
  HeroiconsMailOpenOutline: HeroiconsMailOpenOutline;
  HeroiconsMailOutline: HeroiconsMailOutline;
  HeroiconsMenuAlt1Outline: HeroiconsMenuAlt1Outline;
  HeroiconsMenuAlt2Outline: HeroiconsMenuAlt2Outline;
  HeroiconsMenuAlt3Outline: HeroiconsMenuAlt3Outline;
  HeroiconsMenuAlt4Outline: HeroiconsMenuAlt4Outline;
  HeroiconsMenuOutline: HeroiconsMenuOutline;
  HeroiconsMicrophoneOutline: HeroiconsMicrophoneOutline;
  HeroiconsMinusCircleOutline: HeroiconsMinusCircleOutline;
  HeroiconsMoonOutline: HeroiconsMoonOutline;
  HeroiconsNewspaperOutline: HeroiconsNewspaperOutline;
  HeroiconsOfficeBuildingOutline: HeroiconsOfficeBuildingOutline;
  HeroiconsPaperClipOutline: HeroiconsPaperClipOutline;
  HeroiconsPauseOutline: HeroiconsPauseOutline;
  HeroiconsPencilAltOutline: HeroiconsPencilAltOutline;
  HeroiconsPencilOutline: HeroiconsPencilOutline;
  HeroiconsPhoneIncomingOutline: HeroiconsPhoneIncomingOutline;
  HeroiconsPhoneOutgoingOutline: HeroiconsPhoneOutgoingOutline;
  HeroiconsPhoneOutline: HeroiconsPhoneOutline;
  HeroiconsPhotographOutline: HeroiconsPhotographOutline;
  HeroiconsPlayOutline: HeroiconsPlayOutline;
  HeroiconsPlusCircleOutline: HeroiconsPlusCircleOutline;
  HeroiconsPlusOutline: HeroiconsPlusOutline;
  HeroiconsPrinterOutline: HeroiconsPrinterOutline;
  HeroiconsQrcodeOutline: HeroiconsQrcodeOutline;
  HeroiconsQuestionMarkCircleOutline: HeroiconsQuestionMarkCircleOutline;
  HeroiconsReceiptRefundOutline: HeroiconsReceiptRefundOutline;
  HeroiconsRefreshOutline: HeroiconsRefreshOutline;
  HeroiconsReplyOutline: HeroiconsReplyOutline;
  HeroiconsScaleOutline: HeroiconsScaleOutline;
  HeroiconsSearchOutline: HeroiconsSearchOutline;
  HeroiconsSelectorOutline: HeroiconsSelectorOutline;
  HeroiconsShareOutline: HeroiconsShareOutline;
  HeroiconsShieldCheckOutline: HeroiconsShieldCheckOutline;
  HeroiconsShieldExclamationOutline: HeroiconsShieldExclamationOutline;
  HeroiconsShoppingCartOutline: HeroiconsShoppingCartOutline;
  HeroiconsSortAscendingOutline: HeroiconsSortAscendingOutline;
  HeroiconsSortDescendingOutline: HeroiconsSortDescendingOutline;
  HeroiconsSparklesOutline: HeroiconsSparklesOutline;
  HeroiconsSpeakerphoneOutline: HeroiconsSpeakerphoneOutline;
  HeroiconsStarOutline: HeroiconsStarOutline;
  HeroiconsStopOutline: HeroiconsStopOutline;
  HeroiconsSunOutline: HeroiconsSunOutline;
  HeroiconsSupportOutline: HeroiconsSupportOutline;
  HeroiconsSwitchHorizontalOutline: HeroiconsSwitchHorizontalOutline;
  HeroiconsSwitchVerticalOutline: HeroiconsSwitchVerticalOutline;
  HeroiconsTagOutline: HeroiconsTagOutline;
  HeroiconsTemplateOutline: HeroiconsTemplateOutline;
  HeroiconsTerminalOutline: HeroiconsTerminalOutline;
  HeroiconsTicketOutline: HeroiconsTicketOutline;
  HeroiconsTranslateOutline: HeroiconsTranslateOutline;
  HeroiconsTrashOutline: HeroiconsTrashOutline;
  HeroiconsTrendingDownOutline: HeroiconsTrendingDownOutline;
  HeroiconsTrendingUpOutline: HeroiconsTrendingUpOutline;
  HeroiconsUploadOutline: HeroiconsUploadOutline;
  HeroiconsUserAddOutline: HeroiconsUserAddOutline;
  HeroiconsUserCircleOutline: HeroiconsUserCircleOutline;
  HeroiconsUserGroupOutline: HeroiconsUserGroupOutline;
  HeroiconsUserRemoveOutline: HeroiconsUserRemoveOutline;
  HeroiconsUserOutline: HeroiconsUserOutline;
  HeroiconsUsersOutline: HeroiconsUsersOutline;
  HeroiconsViewBoardsOutline: HeroiconsViewBoardsOutline;
  HeroiconsViewGridAddOutline: HeroiconsViewGridAddOutline;
  HeroiconsViewListOutline: HeroiconsViewListOutline;
  HeroiconsVolumeOffOutline: HeroiconsVolumeOffOutline;
  HeroiconsVolumeUpOutline: HeroiconsVolumeUpOutline;
  HeroiconsXCircleOutline: HeroiconsXCircleOutline;
  HeroiconsXOutline: HeroiconsXOutline;
  HeroiconsZoomInOutline: HeroiconsZoomInOutline;
  HeroiconsZoomOutOutline: HeroiconsZoomOutOutline;
  HeroiconsLibrarySolid: HeroiconsLibrarySolid;
  HeroiconsAdjustmentsSolid: HeroiconsAdjustmentsSolid;
  HeroiconsAnnotationSolid: HeroiconsAnnotationSolid;
  HeroiconsArchiveSolid: HeroiconsArchiveSolid;
  HeroiconsArrowCircleDownSolid: HeroiconsArrowCircleDownSolid;
  HeroiconsArrowCircleLeftSolid: HeroiconsArrowCircleLeftSolid;
  HeroiconsArrowCircleRightSolid: HeroiconsArrowCircleRightSolid;
  HeroiconsArrowCircleUpSolid: HeroiconsArrowCircleUpSolid;
  HeroiconsArrowDownSolid: HeroiconsArrowDownSolid;
  HeroiconsArrowLeftSolid: HeroiconsArrowLeftSolid;
  HeroiconsArrowNarrowDownSolid: HeroiconsArrowNarrowDownSolid;
  HeroiconsArrowNarrowLeftSolid: HeroiconsArrowNarrowLeftSolid;
  HeroiconsArrowNarrowRightSolid: HeroiconsArrowNarrowRightSolid;
  HeroiconsArrowNarrowUpSolid: HeroiconsArrowNarrowUpSolid;
  HeroiconsArrowRightSolid: HeroiconsArrowRightSolid;
  HeroiconsArrowUpSolid: HeroiconsArrowUpSolid;
  HeroiconsAtSymbolSolid: HeroiconsAtSymbolSolid;
  HeroiconsBadgeCheckSolid: HeroiconsBadgeCheckSolid;
  HeroiconsBanSolid: HeroiconsBanSolid;
  HeroiconsBellSolid: HeroiconsBellSolid;
  HeroiconsBookOpenSolid: HeroiconsBookOpenSolid;
  HeroiconsBookmarkAltSolid: HeroiconsBookmarkAltSolid;
  HeroiconsBookmarkSolid: HeroiconsBookmarkSolid;
  HeroiconsBriefcaseSolid: HeroiconsBriefcaseSolid;
  HeroiconsCalendarSolid: HeroiconsCalendarSolid;
  HeroiconsCameraSolid: HeroiconsCameraSolid;
  HeroiconsCashSolid: HeroiconsCashSolid;
  HeroiconsChartBarSolid: HeroiconsChartBarSolid;
  HeroiconsChartPieSolid: HeroiconsChartPieSolid;
  HeroiconsChartSquareBarSolid: HeroiconsChartSquareBarSolid;
  HeroiconsChatAlt2Solid: HeroiconsChatAlt2Solid;
  HeroiconsChatAltSolid: HeroiconsChatAltSolid;
  HeroiconsChatSolid: HeroiconsChatSolid;
  HeroiconsCheckCircleSolid: HeroiconsCheckCircleSolid;
  HeroiconsCheckSolid: HeroiconsCheckSolid;
  HeroiconsCheveronDownSolid: HeroiconsCheveronDownSolid;
  HeroiconsCheveronLeftSolid: HeroiconsCheveronLeftSolid;
  HeroiconsCheveronRightSolid: HeroiconsCheveronRightSolid;
  HeroiconsCheveronUpSolid: HeroiconsCheveronUpSolid;
  HeroiconsClipboardCheckSolid: HeroiconsClipboardCheckSolid;
  HeroiconsClipboardCopySolid: HeroiconsClipboardCopySolid;
  HeroiconsClipboardListSolid: HeroiconsClipboardListSolid;
  HeroiconsClipboardSolid: HeroiconsClipboardSolid;
  HeroiconsClockSolid: HeroiconsClockSolid;
  HeroiconsCloudDownloadSolid: HeroiconsCloudDownloadSolid;
  HeroiconsCloudUploadSolid: HeroiconsCloudUploadSolid;
  HeroiconsCodeSolid: HeroiconsCodeSolid;
  HeroiconsCogSolid: HeroiconsCogSolid;
  HeroiconsCollectionSolid: HeroiconsCollectionSolid;
  HeroiconsColorSwatchSolid: HeroiconsColorSwatchSolid;
  HeroiconsCreditCardSolid: HeroiconsCreditCardSolid;
  HeroiconsCurrencyDollarSolid: HeroiconsCurrencyDollarSolid;
  HeroiconsCurrencyEuroSolid: HeroiconsCurrencyEuroSolid;
  HeroiconsCurrencyPoundSolid: HeroiconsCurrencyPoundSolid;
  HeroiconsCurrencyRupeeSolid: HeroiconsCurrencyRupeeSolid;
  HeroiconsCurrencyYenSolid: HeroiconsCurrencyYenSolid;
  HeroiconsCursorClickSolid: HeroiconsCursorClickSolid;
  HeroiconsDesktopComputerSolid: HeroiconsDesktopComputerSolid;
  HeroiconsDocumentAddSolid: HeroiconsDocumentAddSolid;
  HeroiconsDocumentDownloadSolid: HeroiconsDocumentDownloadSolid;
  HeroiconsDocumentDuplicateSolid: HeroiconsDocumentDuplicateSolid;
  HeroiconsDocumentRemoveSolid: HeroiconsDocumentRemoveSolid;
  HeroiconsDocumentReportSolid: HeroiconsDocumentReportSolid;
  HeroiconsDocumentSolid: HeroiconsDocumentSolid;
  HeroiconsDotsCircleHorizontalSolid: HeroiconsDotsCircleHorizontalSolid;
  HeroiconsDotsHorizontalSolid: HeroiconsDotsHorizontalSolid;
  HeroiconsDotsVerticalSolid: HeroiconsDotsVerticalSolid;
  HeroiconsDownloadSolid: HeroiconsDownloadSolid;
  HeroiconsDuplicateSolid: HeroiconsDuplicateSolid;
  HeroiconsEmojiHappySolid: HeroiconsEmojiHappySolid;
  HeroiconsEmojiSadSolid: HeroiconsEmojiSadSolid;
  HeroiconsExclamationCircleSolid: HeroiconsExclamationCircleSolid;
  HeroiconsExclamationSolid: HeroiconsExclamationSolid;
  HeroiconsExternalLinkSolid: HeroiconsExternalLinkSolid;
  HeroiconsEyeOffSolid: HeroiconsEyeOffSolid;
  HeroiconsEyeSolid: HeroiconsEyeSolid;
  HeroiconsFilterSolid: HeroiconsFilterSolid;
  HeroiconsFlagSolid: HeroiconsFlagSolid;
  HeroiconsFolderSolid: HeroiconsFolderSolid;
  HeroiconsGlobeAltSolid: HeroiconsGlobeAltSolid;
  HeroiconsGlobeSolid: HeroiconsGlobeSolid;
  HeroiconsHashtagSolid: HeroiconsHashtagSolid;
  HeroiconsHeartSolid: HeroiconsHeartSolid;
  HeroiconsHomeSolid: HeroiconsHomeSolid;
  HeroiconsInboxInSolid: HeroiconsInboxInSolid;
  HeroiconsInboxSolid: HeroiconsInboxSolid;
  HeroiconsInformationCircleSolid: HeroiconsInformationCircleSolid;
  HeroiconsKeySolid: HeroiconsKeySolid;
  HeroiconsLightBulbSolid: HeroiconsLightBulbSolid;
  HeroiconsLightningBoltSolid: HeroiconsLightningBoltSolid;
  HeroiconsLinkSolid: HeroiconsLinkSolid;
  HeroiconsLocationMarkerSolid: HeroiconsLocationMarkerSolid;
  HeroiconsLockClosedSolid: HeroiconsLockClosedSolid;
  HeroiconsLockOpenSolid: HeroiconsLockOpenSolid;
  HeroiconsLogoutSolid: HeroiconsLogoutSolid;
  HeroiconsMailOpenSolid: HeroiconsMailOpenSolid;
  HeroiconsMailSolid: HeroiconsMailSolid;
  HeroiconsMenuAlt1Solid: HeroiconsMenuAlt1Solid;
  HeroiconsMenuAlt2Solid: HeroiconsMenuAlt2Solid;
  HeroiconsMenuAlt3Solid: HeroiconsMenuAlt3Solid;
  HeroiconsMenuAlt4Solid: HeroiconsMenuAlt4Solid;
  HeroiconsMenuSolid: HeroiconsMenuSolid;
  HeroiconsMicrophoneSolid: HeroiconsMicrophoneSolid;
  HeroiconsMinusCircleSolid: HeroiconsMinusCircleSolid;
  HeroiconsMoonSolid: HeroiconsMoonSolid;
  HeroiconsNewspaperSolid: HeroiconsNewspaperSolid;
  HeroiconsOfficeBuildingSolid: HeroiconsOfficeBuildingSolid;
  HeroiconsPaperClipSolid: HeroiconsPaperClipSolid;
  HeroiconsPauseSolid: HeroiconsPauseSolid;
  HeroiconsPencilAltSolid: HeroiconsPencilAltSolid;
  HeroiconsPencilSolid: HeroiconsPencilSolid;
  HeroiconsPhoneIncomingSolid: HeroiconsPhoneIncomingSolid;
  HeroiconsPhoneOutgoingSolid: HeroiconsPhoneOutgoingSolid;
  HeroiconsPhoneSolid: HeroiconsPhoneSolid;
  HeroiconsPhotographSolid: HeroiconsPhotographSolid;
  HeroiconsPlaySolid: HeroiconsPlaySolid;
  HeroiconsPlusCircleSolid: HeroiconsPlusCircleSolid;
  HeroiconsPlusSolid: HeroiconsPlusSolid;
  HeroiconsPrinterSolid: HeroiconsPrinterSolid;
  HeroiconsQrcodeSolid: HeroiconsQrcodeSolid;
  HeroiconsQuestionMarkCircleSolid: HeroiconsQuestionMarkCircleSolid;
  HeroiconsReceiptRefundSolid: HeroiconsReceiptRefundSolid;
  HeroiconsRefreshSolid: HeroiconsRefreshSolid;
  HeroiconsReplySolid: HeroiconsReplySolid;
  HeroiconsScaleSolid: HeroiconsScaleSolid;
  HeroiconsSearchSolid: HeroiconsSearchSolid;
  HeroiconsSelectorSolid: HeroiconsSelectorSolid;
  HeroiconsShareSolid: HeroiconsShareSolid;
  HeroiconsShieldCheckSolid: HeroiconsShieldCheckSolid;
  HeroiconsShieldExclamationSolid: HeroiconsShieldExclamationSolid;
  HeroiconsShoppingCartSolid: HeroiconsShoppingCartSolid;
  HeroiconsSortAscendingSolid: HeroiconsSortAscendingSolid;
  HeroiconsSortDescendingSolid: HeroiconsSortDescendingSolid;
  HeroiconsSparklesSolid: HeroiconsSparklesSolid;
  HeroiconsSpeakerphoneSolid: HeroiconsSpeakerphoneSolid;
  HeroiconsStarSolid: HeroiconsStarSolid;
  HeroiconsStopSolid: HeroiconsStopSolid;
  HeroiconsSunSolid: HeroiconsSunSolid;
  HeroiconsSupportSolid: HeroiconsSupportSolid;
  HeroiconsSwitchHorizontalSolid: HeroiconsSwitchHorizontalSolid;
  HeroiconsSwitchVerticalSolid: HeroiconsSwitchVerticalSolid;
  HeroiconsTagSolid: HeroiconsTagSolid;
  HeroiconsTemplateSolid: HeroiconsTemplateSolid;
  HeroiconsTerminalSolid: HeroiconsTerminalSolid;
  HeroiconsTicketSolid: HeroiconsTicketSolid;
  HeroiconsTranslateSolid: HeroiconsTranslateSolid;
  HeroiconsTrashSolid: HeroiconsTrashSolid;
  HeroiconsTrendingDownSolid: HeroiconsTrendingDownSolid;
  HeroiconsTrendingUpSolid: HeroiconsTrendingUpSolid;
  HeroiconsUploadSolid: HeroiconsUploadSolid;
  HeroiconsUserAddSolid: HeroiconsUserAddSolid;
  HeroiconsUserCircleSolid: HeroiconsUserCircleSolid;
  HeroiconsUserGroupSolid: HeroiconsUserGroupSolid;
  HeroiconsUserRemoveSolid: HeroiconsUserRemoveSolid;
  HeroiconsUserSolid: HeroiconsUserSolid;
  HeroiconsUsersSolid: HeroiconsUsersSolid;
  HeroiconsViewBoardsSolid: HeroiconsViewBoardsSolid;
  HeroiconsViewGridAddSolid: HeroiconsViewGridAddSolid;
  HeroiconsViewListSolid: HeroiconsViewListSolid;
  HeroiconsVolumeOffSolid: HeroiconsVolumeOffSolid;
  HeroiconsVolumeUpSolid: HeroiconsVolumeUpSolid;
  HeroiconsXCircleSolid: HeroiconsXCircleSolid;
  HeroiconsXSolid: HeroiconsXSolid;
  HeroiconsZoomInSolid: HeroiconsZoomInSolid;
  HeroiconsZoomOutSolid: HeroiconsZoomOutSolid;
  [key: string]: Component;
}

export type VueHeroiconsInstaller = PluginFunction<HeroiconsPluginOptions>;

export interface Heroicons {
  install: VueHeroiconsInstaller;
  icons: HeroiconsComponents;
}

export default Heroicons;
    